name: PR Preview Build
on: pull_request

jobs:
  build-pr-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install trunk
        run: |
          curl -sL https://github.com/trunk-rs/trunk/releases/download/v0.20.0-alpha.2/trunk-x86_64-unknown-linux-gnu.tar.gz -o trunk-x86_64-unknown-linux-gnu.tar.gz
          tar xzf trunk-x86_64-unknown-linux-gnu.tar.gz
          sudo install trunk /usr/bin/trunk
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install NPM dependencies
        run: npm install

      - name: Set build timestamp
        run: echo "BUILD_TIMESTAMP=$(date --rfc-3339=seconds --utc)" >> $GITHUB_ENV
      - name: Build page
        env:
          BUILD_COMMIT: ${{ github.sha }}
        run: trunk build --public-url /

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
      - uses: actions/upload-artifact@v3
        with:
          name: pr
          path: pr/
