name: Publish

on:
  workflow_call: { }

permissions:
  contents: read
  pages: write
  id-token: write

concurrency: publish

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install trunk
        run: |
          curl -sL https://github.com/thedodd/trunk/releases/download/v0.20.0-rc.1/trunk-x86_64-unknown-linux-gnu.tar.gz -o trunk-x86_64-unknown-linux-gnu.tar.gz
          tar xzf trunk-x86_64-unknown-linux-gnu.tar.gz
          sudo install trunk /usr/bin/trunk

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set build timestamp
        run: echo "BUILD_TIMESTAMP=$(date --rfc-3339=seconds --utc)" >> $GITHUB_ENV

      - name: Build page
        env:
          BUILD_COMMIT: ${{ github.sha }}
        run: trunk build --public-url /patternfly-yew-quickstart

      - name: Create 404.html
        run: |
          cd dist
          cp index.html 404.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
